["Il y a ",plusboucoup," millions de personnes qui dorment dans le monde en ce moment"],
["Aujourd'hui, le Pérou a eu ",tresbocoup," naissances"],
["On dénombre ",bocoup," avions au dessus de la France à cet instant"],
["Environ ",unpeu," millions de clous ont été vendus cette année"],
["Un bureau moyennement encombré compte ",quelqueuh," stylos, contre ",pasmal," pour un bureau très encombré"],
[unpeu," est le nombre moyen de marins dans un bateau de pêche traditionnelle"],
["On estime qu'il y a ",plusboucoup," mégaoctets de photos envoyées chaque minute sur Facebook"],
["Il y avait ",plusboucoup," spectateurs dans les cinémas lyonnais hier soir"],
[pasmal," employés américains sur 100 consultent Facebook au travail"],
["L'Italie exporte ",plusboucoup," véhicules de luxe par an"],
["On dénombre ",plusboucoup," SMS envoyés cette seconde en Europe"],
["Les clubs espagnols de football ont ",bocoupbocoup," licenciés cette année"],
["Il y a ",bocoupbocoup," iPhones dans le monde dont la batterie est 42% actuellement"],
["Environ ",bocoup," pétaoctets de fichiers ont été placé dans la Corbeille aujourd'hui aux États-Unis"],
["Le Brésil a exporté ",bocoupbocoup," tonnes de soja hier"],
["Un orteil est cogné contre le coin d'un lit parisien toutes les ",unpeu," secondes"],
["En Nouvelle-Zélande, un iPhone tombe et se casse toutes les ",unpeu," secondes"],
["On a ",pasmal," fois plus de chance de tomber en courant qu'en marchant"],
["Moins de ",unpeu," français sur 100 savent marcher sur les mains"],
["Un téléphone portable passe ",bocoup," jours par an dans une poche"],
["Twitter fait perdre en moyenne ",pasmal," minutes par jour"],
["Les canadiens mangent ",quelqueuh," fois plus de frites que d'épinards"],
["Chaque année sont gaspillées ",tresbocoup," tonnes de peinture bleue en Inde"],
["On passe en moyenne ",quelqueuh," jours de notre vie à démêler des câbles"],
["La Maison-Blanche reçoit ",tresbocoup," lettres destinées au Père-Noël chaque année"],
["Chaque mois, le Mexique importe ",pasmal," tonnes de dentifrice"],
["L'heure est affichée ",quelqueuh," fois dans un foyer suisse"],
["Les surligneurs sont ",unpeu," fois plus vendus que les crayons de couleur"],
["Moins de ",quelqueuh," internautes sur 100 tiennent leur version de Java à jour"],
["Le rugby est la raison de ",tresbocoup," fractures par an à Toulouse"],
["Les brésiliens achètent une nouvelle ceinture tous les ",unpeu," mois"],
["On fait en moyenne ",pasmal," pas pour se rendre aux toilettes"],
["Les français marchent ",bocoup," mètres par mois en cherchant leurs clés"],
["Il faut en moyenne ",quelqueuh," secondes pour avoir de l'eau chaude depuis un robinet en Angleterre"],
["On maigrit de ",quelqueuh," grammes chaque nuit"],
["Il faut ",pasmal," flocons de neige pour faire un centimètre cube d'eau"],
[pasmal," bibliothécaires sur 100 sont des auteurs frustrés"],
[plusboucoup," canadiens ont réclamé des cookies au travail hier"],
["Les russes devraient dormir ",pasmal," minutes de plus par nuit"],
[plusboucoup," kilogrammes de volaille ont été consommés cette seconde"],
["Chaque minute, ",unpeu," kilogrammes de bonbons sont mangés à Lille"],
["Un brestois éternue ",plusboucoup," fois par an"],
[plusboucoup," personnes écoutent une chanson de System Of A Down en ce moment"],
["Les français se grattent le nez ",quelqueuh," secondes par jour"],
[pasmal," est le nombre moyen de caractères dans un titre de vidéo Youtube"],
["Un stylo plume dépense ",pasmal," centilitres d'encre par kilomètre écrit"],
["Un melon pèse en moyenne ",tresbocoup," grammes"]